[package]
name = "rustwasgi"
version = "0.1.4"
edition = "2024"
readme = "README.md"

[lib]
name = "_rustwasgi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http = "1"
bytes = "1"
http-body = "1"
http-body-util = { version = "0.1", features = ["channel"] }
futures-util = "0.3"
tokio-tungstenite = "0.26"
tungstenite = "0.26"
pyo3-async-runtimes = { version = "0.29.0", features = ["tokio-runtime"] }
rustls = "0.23"
tokio-rustls = "0.26"
rustls-pemfile = "2.2"
arc-swap = "1.7"
rcgen = "0.13"
x509-parser = "0.16"
time = { version = "0.3", features = ["std", "parsing", "formatting"] }
instant-acme = { version = "0.4" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
